
import {
    getAjustes,
    getAsociados,
    getBarrios,
    getCarpetasMedicas,
    getClientes,
    getCondicionesIva,
    getDocumentaciones,
    getEntregasRopa,
    getEstadosCiviles,
    getEstadosDocumentacion,
    getFacturas,
    getFeriados, 
    getLineasDocumentacion,
    getLineasEntregaRopa,
    getLineasServicios,
    getLocalidades,
    getModalidades,
    getMotivos,
    getObjetivos,
    getPrendas,
    getProvincias,
    getRecibos,
    getRoles,
    getServicios,
    getTalles,
    getTiposAjustes,
    getTiposDocumentacion,
    getTiposMotivos,
    getTiposPrendas,
    getTiposTelefonos,
    getUsers,
    getValores,
  } from "./zthunks"; 
  
  export const loadInitialResources = async (dispatch) => {
    const thunks = [
      getAjustes,
      getAsociados,
      getBarrios,
      getCarpetasMedicas,
      getClientes,
      getCondicionesIva,
      getDocumentaciones,
      getEntregasRopa,
      getEstadosCiviles,
      getEstadosDocumentacion,
      getFacturas,
      getFeriados,
      getLineasDocumentacion,
      getLineasEntregaRopa,
      getLineasServicios,
      getLocalidades,
      getModalidades,
      getMotivos,
      getObjetivos,
      getPrendas,
      getProvincias,
      getRecibos,
      getRoles,
      getServicios,
      getTalles,
      getTiposAjustes,
      getTiposDocumentacion,
      getTiposMotivos,
      getTiposPrendas,
      getTiposTelefonos,
      getUsers,
      getValores,
    ];
  
    await Promise.all(thunks.map((thunk) => dispatch(thunk())));
  };
  