
import {
    getAsociados,
    getBarrios,
    getClientes,
    getCondicionesIva,
    getDocumentaciones,
    getEntregasRopa,
    getEstadosCiviles,
    getEstadosDocumentacion,
    getLineasDocumentacion,
    getLineasEntregaRopa,
    getLocalidades,
    getModalidades,
    getObjetivos,
    getPrendas,
    getProvincias,
    getServicios,
    getTalles,
    getTiposAjustes,
    getTiposDocumentacion,
    getTiposPrendas,
    getTiposTelefonos,
    getValores,
    getLineasServicios,
    getMotivos,
    getTiposMotivos,
    getAjustes,
    getFeriados, 
  } from "./zthunks"; 
  
  export const loadInitialResources = async (dispatch) => {
    const thunks = [
      getServicios,
      getLineasDocumentacion,
      getCondicionesIva,
      getEstadosCiviles,
      getModalidades,
      getEstadosDocumentacion,
      getTiposDocumentacion,
      getPrendas,
      getTiposPrendas,
      getTalles,
      getValores,
      getLocalidades,
      getBarrios,
      getProvincias,
      getTiposTelefonos,
      getEntregasRopa,
      getDocumentaciones,
      getClientes,
      getObjetivos,
      getAsociados,
      getLineasEntregaRopa,
      getLineasServicios,
      getMotivos,
      getTiposMotivos,
      getFeriados,
      getTiposAjustes,
      getAjustes,
    ];
  
    await Promise.all(thunks.map((thunk) => dispatch(thunk())));
  };
  