import { configureStore } from "@reduxjs/toolkit";
import {
  AjustesSlice,
  AsociadosSlice,
  AuthSlice,
  ClientesSlice,
  CondicionesIvaSlice,
  DocumentacionSlice,
  EntregaRopaSlice,
  EstadosCivilesSlice,
  EstadosDocumentacionSlice,
  FeriadosSlice,
  LineasDocumentacionSlice,
  LineasEntregaRopaSlice,
  LineasServicioSlice,
  ModalidadesSlice,
  MotivosSlice,
  ObjetivosSlice,
  PrendasSlice,
  RecibosSlice,
  ServiciosSlice,
  TiposAjustesSlice,
  TiposDocumentacionSlice,
  TiposMotivosSlice,
  TiposTelefonosSlice,
  UbicacionesSlice,
  UiSlice,
  valoresSlice,
} from "./slices/zslices";

export const store = configureStore({
  reducer: {
    ajustes: AjustesSlice.reducer,
    asociados: AsociadosSlice.reducer,
    auth: AuthSlice.reducer,
    clientes: ClientesSlice.reducer,
    condicionesIva: CondicionesIvaSlice.reducer,
    documentacion: DocumentacionSlice.reducer,
    entregasRopa: EntregaRopaSlice.reducer,
    estadosCiviles: EstadosCivilesSlice.reducer,
    estadosDocumentacion: EstadosDocumentacionSlice.reducer,
    feriados: FeriadosSlice.reducer,
    lineasDocumentacion: LineasDocumentacionSlice.reducer,
    lineasDocumentacion: LineasDocumentacionSlice.reducer,
    lineasEntregaRopa: LineasEntregaRopaSlice.reducer,
    lineasServicio: LineasServicioSlice.reducer,
    modalidades: ModalidadesSlice.reducer,
    motivos: MotivosSlice.reducer,
    objetivos: ObjetivosSlice.reducer,
    prendas: PrendasSlice.reducer,
    recibos: RecibosSlice.reducer,
    servicios: ServiciosSlice.reducer,
    tiposAjustes: TiposAjustesSlice.reducer,
    tiposDocumentacion: TiposDocumentacionSlice.reducer,
    tiposMotivos: TiposMotivosSlice.reducer,
    tiposTelefonos: TiposTelefonosSlice.reducer,
    ubicaciones: UbicacionesSlice.reducer,
    ui: UiSlice.reducer,
    valores: valoresSlice.reducer,
  },
});
